name: code_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.7.0
  go_router: ^7.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Thin.ttf
          weight: 100
        - asset: assets/fonts/Jost-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Jost-Light.ttf
          weight: 300
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Jost-Black.ttf
          weight: 900
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
